### ISSUE TITLE
Self-closed Tags?

### ISSUE THREAD

**Issue by dev-jonatas-almeida** [olrtg/nvim-emmet#11]
HOLY CHRIST, this an awesome plugin! really appreciate your work , but there is something bothering me

Could you implement an update where tags like img, meta, input,etc close themselves automatically? If not, is there a config file where i can edit the metadata to achieve this behavior?

**Comment by olrtg** [comment]
Hey @feijoes-magicos! Vscode has the same behavior when it comes to those elements because they cannot contain child elements.. and the `/` is optional it seems (although from what I see in my setup, prettier always adds the `/` at the end). Also here in the spec https://www.w3.org/TR/2011/WD-html-markup-20110405/syntax.html#syntax-elements it says that they're optional.

If you still want to enforce this behavior it seems to be possible https://stackoverflow.com/a/53502854. Note that this configuration you should add it to your language server config not in the plugin.
Let me know if that works for you!
